# name: Build and deploy

# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   Deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Pull from github and restart containers
#       uses: appleboy/ssh-action@master
#       env:
#           SERVER_DIRECTORY: ~/new-main
#       with:
#         host: ${{ secrets.HOST }}
#         USERNAME: ${{ secrets.USERNAME }}
#         PORT: ${{ secrets.PORT }}
#         KEY: ${{ secrets.SSHKEY }}
#         script: |
#           cd $SERVER_DIRECTORY
#           git pull
#           ./ncm --env prod artisan down --no-interaction
#           ./ncm --env prod down
#           ./ncm --env prod up --wait
#           ./ncm --env prod composer install --no-dev --ansi --no-interaction
#           ./ncm --env prod artisan storage:link --no-interaction --force
#           ./ncm --env prod artisan package:discover --no-interaction
#           ./ncm --env prod artisan migrate --no-interaction --force
#           ./ncm --env prod artisan config:cache --no-interaction
#           ./ncm --env prod artisan route:cache --no-interaction
#           ./ncm --env prod artisan view:cache --no-interaction
#           ./ncm --env prod artisan icons:cache --no-interaction
#           ./ncm --env prod artisan up --no-interaction